grpc:
  port: 6566

spring:
  application:
    name: tests-service-api
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: tests_db

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false

#spring.data.mongodb.uri: tests_db://srv_tests:0000@localhost:27017

